/*
    Auto-generated by Assistant Trainer
    Threat: custom_ransomware
    Severity: high
    Generated: 2026-08-20T05:00:08
*/

rule learned_custom_ransomware : high
{
    strings:
        $r1 = "encrypt_files" ascii nocase
        $r2 = "bitcoin_wallet" ascii nocase
        $r3 = ".locked" ascii wide nocase
        $r4 = "vss_delete_shadow" ascii nocase
        $r5 = "YOUR FILES HAVE BEEN ENCRYPTED" ascii wide nocase
        $r6 = "pay the ransom" ascii wide nocase

    condition:
        // Require multiple ransom-specific indicators
        3 of ($r*) and uint16(0) == 0x5A4D
}
