/*
    Auto-generated by Assistant Trainer
    Threat: test_worm
    Severity: high
    Generated: 2026-08-20T05:33:28
*/

rule learned_test_worm : high
{
    strings:
        $w1 = "WNetAddConnection2" ascii
        $w2 = "NetShareEnum" ascii
        $s1 = "\\\\ADMIN$" ascii wide
        $s2 = "\\\\C$" ascii wide
        $s3 = "\\\\IPC$" ascii wide
        $r1 = "spread_network" ascii nocase
        $r2 = "smb_exploit" ascii nocase

    condition:
        ((1 of ($w*) and 2 of ($s*)) or
        (2 of ($r*) and 1 of ($w*))) and
        uint16(0) == 0x5A4D
}
