/*
    Auto-generated by Assistant Trainer
    Threat: auto_trojan
    Severity: high
    Generated: 2026-08-20T05:19:34
*/

rule learned_auto_trojan : high
{
    strings:
        // Process injection indicators
        $i1 = "CreateRemoteThread" ascii
        $i2 = "VirtualAllocEx" ascii
        $i3 = "WriteProcessMemory" ascii
        $i4 = "NtUnmapViewOfSection" ascii
        $i5 = "QueueUserAPC" ascii

    condition:
        // Require multiple injection APIs (strong trojan indicator)
        3 of ($i*) and uint16(0) == 0x5A4D
}
