/*
    Auto-generated by Assistant Trainer
    Threat: auto_ransomware
    Severity: critical
    Generated: 2026-08-20T05:19:34
*/

rule learned_auto_ransomware : critical
{
    strings:
        // Ransomware behavior indicators
        $r1 = "vssadmin delete shadows" ascii wide nocase
        $r2 = "wbadmin delete catalog" ascii wide nocase
        $r3 = "bcdedit /default" ascii wide nocase
        $r4 = "CryptEncrypt" ascii
        $r5 = "BCryptEncrypt" ascii
        $r6 = "CryptGenKey" ascii

    condition:
        // Require ransom behavior commands plus crypto APIs
        (1 of ($r1, $r2, $r3) and 2 of ($r4, $r5, $r6)) and
        uint16(0) == 0x5A4D
}
