# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Microsoft Security DevOps (MSDO) is a command line application which integrates static analysis tools into the development cycle.
# MSDO installs, configures and runs the latest versions of static analysis tools
# (including, but not limited to, SDL/security and compliance tools).
#
# The Microsoft Security DevOps action is currently in preview.
#
# For more information about the action, see https://github.com/microsoft/security-devops-action
#
# Note: this workflow does not integrate your GitHub organization with Microsoft Defender for DevOps.
# You must create the integration and grant permissions before results can be reported back to Azure.
# Official docs: https://learn.microsoft.com/en-us/azure/defender-for-cloud/quickstart-onboard-github

name: "Microsoft Defender for DevOps"

on:
  push:
    branches: [ "security-v2" ]
  pull_request:
    branches: [ "security-v2" ]
  schedule:
    - cron: '24 12 * * 3'

jobs:
  MSDO:
    permissions:
      contents: read
      security-events: write
      actions: read
    # currently only windows latest is supported
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run Microsoft Security DevOps
      uses: microsoft/security-devops-action@e94440350ed10e2806d47cd0d7504a2c51abdbe9 # v1.6.0
      id: msdo
    - name: Upload results to Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.msdo.outputs.sarifFile }}
